[versions]
activityCompose = "1.8.0"
coreKtx = "1.12.0"
espressoCore = "3.5.1"
gradle = "8.2.0"
junit = "4.13.2"
junitVersion = "1.1.5"
kotlin = "1.9.0"
composeMaterial = "1.5.4"
composeMaterial3 = "1.2.0-rc01"
naviVersion = "2.7.5"
googleGson = "2.10.1"
coroutine = "1.7.3"
hilt = "2.48.1"
hiltCompose = "1.0.0"
room = "2.6.1"
holixBottomSheetDialog = "1.4.0"
gms = "4.4.0"
constraintlayout = "1.1.0-alpha13"
ktor = "2.3.6"
serialization = "1.9.0"
datastore = "1.0.0"
crashlytics = "2.9.9"
ksp = "1.9.0-1.0.13"
glide = "1.0.0-beta01"
exoplayer = "1.2.0"
card = "1.0.0"
licenses = "17.0.1"
licensesPlugin = "0.10.6"

complieSdk = "34"
minSdk = "24"
versionCode = "51"
versionName = "2.0.00"
composeCompiler = "1.5.2"

[libraries]
androidx-card = { module = "androidx.cardview:cardview", version.ref = "card" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "naviVersion" }
androidx-navigation-hilt = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hiltCompose" }

androidx-compose-bom = "androidx.compose:compose-bom:2023.10.01"
androidx-compose-ui = { module = "androidx.compose.ui:ui" }
androidx-compose-ui-graphics = { module = "androidx.compose.ui:ui-graphics" }
androidx-compose-ui-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
androidx-compose-ui-test = { module = "androidx.compose.ui:ui-test-junit4" }
androidx-compose-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest" }
androidx-compose-material = { module = "androidx.compose.material:material", version.ref = "composeMaterial" }
androidx-compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "composeMaterial3" }
androidx-compose-constraintlayout = { module = "androidx.constraintlayout:constraintlayout-compose", version.ref = "constraintlayout" }
androidx-datastore = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
holix-bottomsheetdialog-compose = { module = "com.holix.android:bottomsheetdialog-compose", version.ref = "holixBottomSheetDialog" }

test-androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCore" }
test-androidx-junit = { module = "androidx.test.ext:junit", version.ref = "junitVersion" }
test-junit = { module = "junit:junit", version.ref = "junit" }
google-gson = { module = "com.google.code.gson:gson", version.ref = "googleGson" }
coroutine-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutine" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }
glide = { module = "com.github.bumptech.glide:compose", version.ref = "glide" }

ktor-android = { module = "io.ktor:ktor-client-android", version.ref = "ktor" }
ktor-serialization-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }

androidx-media-exoplayer = { module = "androidx.media3:media3-exoplayer", version.ref = "exoplayer" }
androidx-media-ui = { module = "androidx.media3:media3-ui", version.ref = "exoplayer" }

firebase-bom = "com.google.firebase:firebase-bom:32.6.0"
firebase-analytics = { module = "com.google.firebase:firebase-analytics" }
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics" }
firebase-auth = { module = "com.google.firebase:firebase-auth" }
firebase-firestore = { module = "com.google.firebase:firebase-firestore" }

android-licenses = { module = "com.google.android.gms:play-services-oss-licenses", version.ref = "licenses" }
android-licenses-plugin = { module = "com.google.android.gms:oss-licenses-plugin", version.ref = "licensesPlugin" }

[plugins]
android-application = { id = "com.android.application", version.ref = "gradle" }
android-library = { id = "com.android.library", version.ref = "gradle" }
kotlin = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "serialization" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
google-service = { id = "com.google.gms.google-services", version.ref = "gms" }
firebase-crashlytices = { id = "com.google.firebase.crashlytics", version.ref = "crashlytics" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
